Exemple fixing
CariusLars/ar_flutter_plugin pull request #154
Opened 2022-11-11 11:58 UTC by giovannicampagnolo

Fixing all the example with updating null-safety and fix also scaling on ios models

2022-11-11 17:37 UTC, nsvetlakov approved these changes

2022-11-16 14:27 UTC, giovannicampagnolo commented
@CariusLars

2022-11-17 18:46 UTC, CariusLars requested changes
Added a comment. Two other points:

1. If you adapt the scaling on iOS, isn't the duck in the example application way bigger than on android now?
2. could you add an entry in changelog.md for your patch version and update the version referenced in the readme.md, please?

Thanks a lot for your contribution!

2022-11-17 18:46 UTC, CariusLars commented on example/pubspec.yaml
> +  app_settings: 4.1.6
why did you add these dependencies?

2022-11-18 08:14 UTC, giovannicampagnolo commented
ok @CariusLars then the scaling 0.01 is for duck now i fix

2022-11-18 08:26 UTC, giovannicampagnolo commented
i made the request fix if you want to check @CariusLars

2022-11-18 08:27 UTC, giovannicampagnolo commented on example/pubspec.yaml
> +  app_settings: 4.1.6
it is my error now i fix

2022-11-18 22:58 UTC, CariusLars requested changes
thanks for the updates! two more small comments left in the code and could you please also update the readme to reference your new version 0.7.3 in the installation section?

2022-11-18 22:58 UTC, CariusLars commented on ios/Classes/ArModelBuilder.swift
> +                child.scale = SCNVector3(1,1,1) // Compensate for the different model dimension definitions in iOS and Android (meters vs. millimeters)
can you revert this as well please?

2022-11-18 22:58 UTC, CariusLars commented on pubspec.yaml
> +  #flutter: ">=1.20.0"
why did you comment this out?

2022-11-19 08:50 UTC, giovannicampagnolo commented on pubspec.yaml
> +  #flutter: ">=1.20.0"
i fixed also this

2022-11-19 08:50 UTC, giovannicampagnolo commented on ios/Classes/ArModelBuilder.swift
> +                child.scale = SCNVector3(1,1,1) // Compensate for the different model dimension definitions in iOS and Android (meters vs. millimeters)
fix

2022-11-19 08:50 UTC, giovannicampagnolo commented
@CariusLars i resolve the last issues 

Thank you

2022-11-19 21:32 UTC, merged

2022-11-19 21:32 UTC, CariusLars commented
merged it, thanks a lot for your contribution @giovannicampagnolo !